import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Scene from "@/components/Scene";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* The WebGL scene lives in the layout so it stays mounted across
            route changes (home <-> panel routes); pages only drive the URL. */}
        <Scene />
        {children}
      </body>
    </html>
  );
}
